name: vivit
favicon: null
layout_spectrum: 0.0359
typography_spectrum: 0.35643
title: Bij Vitiv kunt u terug voor al uw biologische producten. Ook staan er heerlijke recepten met deze gezonde ingrediënten op de site.
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#8ac543'
    - '#046739'
    - '#518b68'
    - '#adcbbc'
  brandStrength: 1
  lightness: 0.375
  saturation: 1
  rhythmicContrast: 1
purpose: []
