name: vivit
favicon: null
layout_spectrum: 0.14691253961063921
typography_spectrum: 0.7314536347985268
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.7411545107606798
  lightness: 0.23610812332481146
  saturation: 0.4481205327901989
  rhythmicContrast: 0.564731608144939
purpose: []
