name: vivit
favicon: null
layout_spectrum: 0.8606
typography_spectrum: 0.14106
title: Bij Vitiv kunt u terug voor al uw biologische producten. Ook staan er heerlijke recepten met deze gezonde ingrediënten op de site.
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#22323b'
    - '#159126'
    - '#816361'
    - '#ca2f20'
  brandStrength: 0.8125
  lightness: 0.6875
  saturation: 0.625
  rhythmicContrast: 0.5
purpose: []
