name: vivit
favicon: null
layout_spectrum: 0.43156
typography_spectrum: 0.78714
title: Bij Vitiv kunt u terug voor al uw biologische producten. Ook staan er heerlijke recepten met deze gezonde ingrediënten op de site.
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fcfcfc'
    - '#030303'
    - '#bfd3dc'
    - '#324041'
    - '#73848b'
  brandStrength: 0.3125
  lightness: 0.625
  saturation: 0.625
  rhythmicContrast: 0.25
purpose: []
