name: vivit
favicon: null
layout_spectrum: 0.58013
typography_spectrum: 0.50667
title: Bij Vitiv kunt u terug voor al uw biologische producten. Ook staan er heerlijke recepten met deze gezonde ingrediënten op de site.
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#22323b'
    - '#159126'
    - '#816361'
    - '#ca2f20'
  brandStrength: 0.3125
  lightness: 0.9375
  saturation: 0.375
  rhythmicContrast: 0
purpose: []
